apiVersion: v1

kind: Service

metadata:

  name: web-service

  labels:

    env: testing
spec:

  selector:

    env: testing
  type: NodePort
  ports:

    - nodePort: 31000
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
       env: testing
  template:
    metadata:
     name: myweb-pod
     labels:
       env: testing
    spec:
      containers:
      - name: myweb-con
        image: aju121/myweb:latest
        ports:
        - containerPort: 80
          name: webserver
       